version: "3.9"
services:
  app:
    build: ./docker/php
    volumes:
      - ./app:/www
    depends_on:
      - db

  web:
    build: ./docker/ngnix
    ports:
      - 8080:80
    volumes:
      - ./app:/www
    depends_on:
      - app

  db:
    build: ./docker/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
